export const TABLES = {
  ACCOUNTS: 'accounts',
  BILL_SHEET_ITEMS: 'bill_sheet_items',
  CASES: 'cases',
  COMMISSIONS: 'commissions',
  COMMUNICATIONS: 'communications',
  CONTACTS: 'contacts',
  DISTRIBUTORS: 'distributors',
  DISTRIBUTOR_PRODUCTS: 'distributor_products',
  FACILITIES: 'facilities',
  MANUFACTURERS: 'manufacturers',
  NOTIFICATIONS: 'notifications',
  PAY_PERIODS: 'pay_periods',
  PO_CHASE_LOG: 'po_chase_log',
  PO_EMAIL_LOGS: 'po_email_logs',
  PURCHASE_ORDERS: 'purchase_orders',
  PUSH_SUBSCRIPTIONS: 'push_subscriptions',
  REFERRALS: 'referrals',
  REFERRAL_PAYOUTS: 'referral_payouts',
  SURGEONS: 'surgeons',
  USERS: 'users',
};
